apiVersion: apps/v1
kind: Deployment
metadata:
  name: Flask-app-display
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: Flask-app-container
        image: 1759/e2e-newpipeline-production:1.1.0-39
        ports:
        - containerPort: 5000
