apiVersion: v1
kind: Service
metadata:
  name: flask-app-svc
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: flask-app
  ports:
    - port: 80
      nodePort: 32000
      targetPort: 5000